services:
  - type: web
    name: globetrotter-api
    env: node
    region: singapore # or your preferred region
    buildCommand: cd /opt/render/project/src && npm install && npm run build
    startCommand: cd /opt/render/project/src && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /api/health
    plan: free # Specify the free tier
    instance: basic # Use the basic instance type
